In [1]:
import numpy as np
list_ = ['1', '2' ,'3' ,'4' ,'5']
array_list = np.array(object = list_)

In [29]:
#Q1.

#Yes, there is a difference in the data types of variables list_ and array_list. The variable list_ is a Python list, while the variable array_list is a Numpy array.
type(list_)

list

In [30]:
type(array_list)

numpy.ndarray

In [31]:
#Q2.

print("Data types of elements in list_:")
for element in list_:
    print(type(element))
    
print("\nData types of element in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of element in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [32]:
#Q3.

array_list = np.array(object = list_, dtype = int)

# Yes, there will be a difference in the data type of the elements present in array_list after the specified change. In the updated array_list, the elements will be converted to integers due to the specified dtype = int.

In [33]:
print("Data types of elements in list_:")
for element in list_:
    print(type(element))
    
print("\nData types of element in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of element in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [34]:
#Q4.
num_array = np.array([[1, 2, 3] , [4, 5, 6]])

In [35]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
num_array.shape

(2, 3)

In [37]:
num_array.size

6

In [38]:
#Q5.
zeroes_array = np.zeros((3,3))

In [39]:
zeroes_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
#Q6.
import numpy.matlib as nm
identity_array = nm.eye(5)
identity_array

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])